### ISSUE TITLE
Issues with small tuple example

### ISSUE THREAD

**Issue by jack-williams** [SimonMeskens/TypeProps#7]
I might be implementing this wrong, but here is a small example I ran into trouble with. I extended the sample code posted in the playground [here](https://agentcooper.github.io/typescript-play/#code/C4TwDgpgBArgdgazgewO5ygXigbwL5QA+UcMANmUbHACYQBmAlnBDQNwBQHA9N1AGLwAxsGQAnDs2AQx9AIZDoAZWBzgjIYLgjxAHgDiAPlwcoZqAFs5YXfygQAHtNoBnKPogsxGg4YA0UACqhgAUpuYRwGJycC704hYAXFAhcskACnLRFhDSYi62hgDaAAwAugCUWMaBfuERZlZgYHIARmQQyfz1UBXJHl4+-AFFgWWGnHhcvFAAog5yFmAdLhxCyLHAUFnRIFo6Yskqahr7omK6MSBF41gmEU3JugCCAQBCofRwyanJz1WYYxvALyP43PpQN43ar3BpmMS5GBiDDyAB0TRCXwqnAiUzwnHWmygyFaACsICIzuIjqp1JphOddCTySJjNgcD1HlAXu9Pt8UmkoP8YcCoKChRC3jCOXD4YjkWK4Ji5NieniCRsXFtSBQ2h0qYcoMc6QamWSKVtiDrKMR4HQmCwaGzYY1rE9XpDQj0Il8foLhYDIXVZWL-VRrVQ7QxmKwepLw+QbdR7TGaNLveYEcAkSi5FAAITYKMO1hQAD8iuVVWS8hx5nVXEJWqgNGQMHaMjuIQcyVIFlaMgBxgcUAAVFAAEycNaarYONzYHZyPYM8To6whVvtjpiEYAFgCE8qbCgM3nvZg-ZkNxnRJH2GZFoN67Am7bHd3UD3E+xp74PZIS8BwkJs5wAOUTO5rT1CBnwxLcPwCa1fzPCCKAvChb2bBwlGQHIoMTGC4I3BCdwCPdtjcPtgMjWho0dFD-1wnILyvMRaJTR1G1nMVV0NY1Tj43R4CQNAMGIK4bmdGVzAxL4QRVF0GizHMhTEXZUUYFxnnU5cqwzOEKyXFdtHOF9MTgBSKgMhoazzQtk3o2MQxDCtH0pPjzPk0NrJc2UMLIIjPLkyyfLrMwGywrYQAXXjTLXeD3zIqAigPSdjz-KAYtY4Cb1ArK7noYKSKSmRyJ-E8ZhAHKZCirK0MobAivisRzNIsrAIoRj6sTAK6pAZjoCa4rX3az9v0owC2I4pyaG6ga8M6KaaNtOiSxoaY+HSMggOYABzSQ4DyeRFCgAAVcAIHSMRkDAAozrufAAkybI3EcZwaDcHTdgAGUYBAIEuOAQGdFgADcZGMGSzGM5JoYaZh6BkZIHvezxPrU3ZdERztnmMCsimeMooF7CAIbEcKGlAsQYBEDIskWFxSjKG5KfxHprThmyccNCM0dcc7yxS8GZGJ0nycpiJqdp4AArZyni1TLmQx55JFcdewnHRtwHoJkWxDFkgyZkSXzGlunHPW+WengeI7WV2VVZSsCNgamDdDOwwylNsxzdlqAXsZ5nramDhQEgKAAFk1CEAALD3nVRrWBZ5oIegrEJ8E1j63ECIWrhslHLuu26CmCIp5iEHa6F0AGQGQehzuLm67oCAAiW221oNuvaKNuebbyps+1o3yfTqAO7gO3u56B24SKABpCAQCgZg5gcKuYBruuG6byAS9bifO7tHuykSGyLv3lv7uKJeQBZ-up5kQfh4F-WbIrfWSagO+1Qrjfq6Ax3o3S+V1r7t2Pt3L2399bTjDpdAODMch5BvncUBB8b5FGjsAOOCcH4D29lwcO0ABgyB8D0M6wZzCBwsG9ZOGNvrLj+gDIGIM7iMJAMwwGVx-A9ETs3UuHtnpIJcMUbBuDPYPz9oPaczURCMA2FAbMywIDRxsK8YEdh+YYwEvSFqhRQhkH6J4MhQhbB+EJuMEEPwAIBiBBCUh3gzHDCKEUYEbwyi3HhvlJokBDS-AlDCNxfgPF3HvMYIo9BuwVD8FEhwFRCERBUgqORZkMS+I6mQVUod8pgzkDtCALgapiGhNgIoABGPwE4-AAGYyh1QRC4cgWxsDKI6Go3Q1EOpdM-D0qSIQ8kFJcAEbsxShxQBHAAaigOU6yQA).
```ts
function tupleMap<A,B,F extends StaticFunctor<F>>(l: Generic<F,[A]>, f: (x: A) => B): Generic<F,[[B,B]]> {
    const mapper: (a: A) => [B,B] = x => [f(x),f(x)];
    return functor.map(mapper, l);
}

const values: number[] = [1,2,3]
const result = tupleMap(values, (x: number) => x + 1)
```

The implementation of `tupleMap` doesn't type-check, it doesn't seem to like `mapper`[1]. Also, the call-site doesn't type check, though it does work if you explicitly instantiate the parameters:
```ts
const result = tupleMap<number, number, number[]>(values, (x: number) => x + 1)
```
Is using `number[]` the correct way to pass the functor type? 

[1] Error message:
```ts
Argument of type '(a: A) => [B, B]' is not assignable to parameter of type '(a: TypeProps<TypeProps<F, [A]>[Match<F>]["construct"], never>[Match<TypeProps<F, [A]>[Match<F>][...'.
  Types of parameters 'a' and 'a' are incompatible.
    Type 'TypeProps<TypeProps<F, [A]>[Match<F>]["construct"], never>[Match<TypeProps<F, [A]>[Match<F>]["con...' is not assignable to type 'A'.
      Type '{} | NonNullable<TypeProps<F, [A]>[Match<F>]["construct"]>' is not assignable to type 'A'.
        Type '{}' is not assignable to type 'A'. [2345]
```

**Comment by SimonMeskens** [comment]
You're overcomplicating it. You know what the specific types are, so you can just do this:
```ts
function tupleMap<A, B>(
    l: A[],
    f: (x: A) => B
) {
    const mapper: (a: A) => [B, B] = x => [f(x), f(x)];
    return functor.map(mapper, l);
}

const values = [1, 2, 3];
const result = tupleMap(values, (x: number) => x + 1);
```

**Comment by SimonMeskens** [comment]
Most of the time, inference works and you don't even need to specify anything related to Functor

**Comment by jack-williams** [comment]
Does the signature `tupleMap<A, B>(l: A[], f: (x: A) => B)` not fix the functor to be an array? I wouldn't be able to use that function on other functor instances like `Maybe<A>`. I was trying to write one that was generic over the container.

**Comment by SimonMeskens** [comment]
Ah, sorry, I misunderstood, you want this one then:

```ts
function tupleMap<F,B>(l: F, f: (x: Parameters<F>[0]) => B): Generic<F,[[B,B]]> {
    const mapper: (a: Parameters<F>[0]) => [B,B] = x => [f(x),f(x)];
    return functor.map(mapper, l);
}

const values = [1,2,3]
const result = tupleMap(values, (x: number) => x + 1)
```

**Comment by jack-williams** [comment]
Yep that works, cheers!

Also works for:
```ts
function tupleMap<A extends Parameters<F>[0], B, F extends StaticFunctor<F>>(l: Generic<F,[A]>, f: (x: A) => B): Generic<F,[[B,B]]> {
    const mapper: (a: A) => [B,B] = x => [f(x),f(x)];
    return functor.map(mapper, l);
}
```
