### ISSUE TITLE
Data-type-generic lists sample by Asad Saeeduddin

### ISSUE THREAD

**Issue by SimonMeskens** [SimonMeskens/TypeProps#9]
@masaeedu
```ts
const Arr = (() => {
  const Nil = [];
  const Cons = head => rest => [head, ...rest];
  const match = ({ Cons, Nil }) => a =>
    a.length === 0 ? Nil : Cons(a[0])(a.slice(1));

  return { Nil, Cons, match };
})();

const GenericList = ({ Cons, Nil, match }) => {
  // Misc
  const length = match({ Nil: 0, Cons: _ => rest => 1 + length(rest) });

  // Functor
  const map = f =>
    match({ Nil, Cons: head => rest => Cons(f(head))(map(f)(rest)) });

  return { length, map };
};

console.log(GenericList(Arr).length([0, 1, 2]));
// 3
console.log(GenericList(Arr).map(x => x * 2)([1, 2, 3]));
// [2, 4, 6]
```

[Playground: With TypeProps](https://agentcooper.github.io/typescript-play/?target=5#code/MYewdgzgLgBAhgJwXAnjAvDAFFglBgPhgG8AoGCmUSWMASwBsMYBtAXXghjAFMA3HgnYBucpWrQq4LpgA8AQQJYAFjzgATAFwx5+dESwIe0bfPa5T7Qq1UaANDAB0zo9DajKUmjAC2cKMDKzApKZJ6eEnZi4dyM0TAAvtphMeES2ipqWjp6Bq5Qlmy5MADiPLwIdMAAsuAaIR6pnvQMpo0xCcVYcKZIqCFdcI4M5QDmUEHoUzAADDAA-LFM2hLdLDNF3Y4QDFU8WACMuMei8UZQAK4IYCRLDpG+-oGJop14pxKwZRVVADJ0kjkJRgPAAHlByuouN9BFVamB6nAwCgCKF4pF4i0op4-AFlKQkiR4hFpNoQlhialbNl5JSKMVZAAxEHgyHQ8qwmp1dSyEqowzGAowRnFGGVLkInmMhyKdrhFraMVw7m8ghynFPZTkgD6yTp8sYbX1JMgGWNVKypnN9OsTJZELAUNKHPF8PqfKU+W0IusSol9Vl+s6GS9zp+-p5fNFLuVkoa8U61hSFAA9CmYNUAcB0dJYCMwONlGTmWCHU6-W7I-zQz79NwLj4AEaCZi4wJYZMG1qzbGpdIwbXWfLWA4wADUMHzhYF0FwCdwp08aeFFzAwCgIAQOe8fgADmT5A4AEJKfUAMwyPRy1iP8S6dtLbLDnMrvJl-N2JmF0fDr+lMBPPQYDPQhrUePEOzuLwIG0akh0FaxVjPTINGOLA9ywM9cBnKBjkSBdSDOHhLmuW4pwmBw9xeAlThGWA4GYP1-mgWQkRQdglEQZAUFwYYxgmLB1gcA4HAAJiKYQYGXK8wAbZstwkEARmGEBRm6AjlwAZlIOiYEbRiY2AZioFY5EOO6PoeMcDCsFBbRZKbQRilBGAACoYFE7CWBEjyHE0iSpPTRt7LkwR2FIRTlIYVT3lIZcWFEhwABYHAANjYQjCOXeQABEABVCLBXdN1gOgwAhBAzzgYAeAzbkAAUEBAXcIFkPLmGIBIHHqxA4B8LhH0dLh5Es-4AGseFMlFmF4AQECIYhEkK0FioQWAoBQXdaorFV-3kZg2KITA-SZBwWHkNgHErRrmta-9zrYVFRCKkqYA2ra6slHrkB8YjBCZI6YG+vq-oQO6roapqWoBgh1ncZbVtK8rBCqmrPvdBb4mXRlV3XTcsfTKjNEvGAAFoiEbfByZgdqGOp9rG3iPc2ocABVU8migZBIDPTcfEvbQ8uKVm72Le0nx2uMSgcPL+R8bkqm9H8X12tm1UIpd00rAmqGUOAypgYnsDpogGap034DJi3GYiPWypZmBWfFobn1dFUPQpTnuYgXmEH543BeF0WYAfVkXcl90ZblhXgCV6xWcXShlxAECjZNmn4HiFO2s4wPFUM19pZp9WEkyuL0zyzaeBulqsvTAB1fWoDK0ZgM3GBdyhlsN13N6q9Id7atXMawBAAB3G5ME6mAAB96wYJg59XdQeDPMqeHUU4yoq1Hasrraa9a9qp66oHev652nRG7jxsmw6Zv4QRMc8LjUD1JoyrPQRBcv4bLNkT+LZFALFYBdQ23BH4IHVOIXMCALjrm0MDfqcMRAJjlLJBe79UiAIQCFBev8M6LBYLNQQHB7KQOgRQT4cCEHzwYHKBIcpl6r3XtkTsngcHaGYWvXg6gCHtSISQhAZCIFzUodBLm8ChTcNYQwphYBebLywTEThrAABy4A1EXAXnARsIwc7wyaNQqRiDz4QDhnIgkhFB4Zk1DnZg7VBpOhwY7eIiwOwJAISLJoiw2L6kFlXQ+sh2YsAAKKgmAAwC4K9ZD6gmigFONNAlQwgL2GIAAiVcijHTpP1AQNgLB0k4PSUUAhQi3EwEyQokAy9cmeGUeEFgABpHgaADbhMidEya8TEn72rikhwVTsnqHSfkgJB8UmxKaAVJosMWkoAKUUhRggSllMgfqRY5SmjaHmQmMJESokxJ6SBPph9BlZJqTk-J8RyFiOsVXM+P1QatXiHlNJMAADyc0x6VAhAQ9hlBmkwANscz53zfk8DYA0j+yzcE6FGnQCaU11ZNBNNAGh0iwAj3HmAcRpdPCeKnvqIFILWmJK+YIH5dAIRQqJKiygqjr6oFvsi8RaLJG0OHqPCeeKEzvJylUZudQEBoCcVwAFFASU3FBQK9cdBhULOhdg2FvQb6IrvsiFF9KJEYq4Vi7luKgwJmYBShAVK-litEYICppzJmyxuTAAAwiAJs682rJNujnBwprzU8AIPEQGsqhUIhFSwaodjZaLOKfDAeDyTqvPeUggaYcr4IqRffTATKUAssOu8n1EL-nEqacC6VZKQL5upZC5IJav5wq5TiySxjOX6pxUtAlHVWDFtJQk8t4LK20sWqo+tPKdUmJgMOm4nj8WUEBhWi1KauBbMoIsW1nq3mPL6hAWG4a8QGMKU2qAJSHXOtdbwd1Ey13dTMQQb1faITbojfk-dsCpElNODYk9jY3XrvZh1eIUqYCgqwO1AAZI7XAtLi2WtBd45djtmkZXqTAKDC7ANlsITTBD4DymMKAA)

**Comment by SimonMeskens** [comment]
Added playground link with types, you can also find the sample under ['examples/pattern-matching/list.ts'](https://github.com/SimonMeskens/TypeProps/blob/master/examples/pattern-matching/list.ts)

**Comment by SimonMeskens** [comment]
@masaeedu, I haven't seen you reply anything, so I'm going to assume this sample is typed correctly and close this. Feel free to ask me to open again if I'm wrong. I know this could potentially use a more generic definition for the nil/cons/match construct that is compatible with the other samples, but I couldn't figure out a way.

**Comment by masaeedu** [comment]
Sorry, been busy with other stuff. AFAICT the results look good, it's producing `number` and `number[]` as it should. I'm afraid I can't be too much help with verifying the correctness of the other stuff.

**Comment by SimonMeskens** [comment]
That's good enough for now then. I might look into a more generic ADT pattern matcher type later. Just wanted to do some housekeeping :)
